name: Build then Publish LaTeX document
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:    
    - uses: actions/checkout@v3
    - name: Create Tag
      id: create_tag
      run: |
        tag=v$(date +%Y%m%d.%H%M%S)
        echo "::set-output name=tag::$tag"

    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: ${{ steps.create_tag.outputs.tag }}
        draft: true
        prerelease: false

  publish:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3    
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: DjordjeTanaskovicCV.tex
    
    - name: Upload PDF file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: DjordjeTanaskovicCV.pdf
        asset_name: DjordjeTanaskovicCV.pdf
        asset_content_type: application/pdf

    - name: Publish PDF file
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.release.outputs.release_id }}
    - name: Clean old releases
      uses: eregon/keep-last-n-releases@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        n: 3
        remove_tags_without_release: true
